version: '3.8'

services:
  celery:
    build:
      context: celery/
      dockerfile: Dockerfile
    container_name: celery_container
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    restart: always

  redis:
    image: "redis:alpine"
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
