version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: yandex-base
    container_name: base
    env_file:
      - .env

  telegram:
    build:
      context: .
      dockerfile: Dockerfile.telegram
    container_name: telegram_container
    depends_on:
      - base
    env_file:
      - .env
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_container
    depends_on:
      - redis
      - base
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    restart: always

  redis:
    image: "redis:alpine"
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
